language: node_js
sudo: false

script: "/bin/date"

node_js:
  - 0.10

install : npm install
script  : npm start

deploy:
  provider: opsworks
  access_key_id:
    secure: Mh9tO5/r696QdGyKz5jEXN8BkHy0S+2omGe+QYdEY9UBDMnqpUamkWGFpzARK5uTelc3yy70bn+QMrs1kDWz176SxetChOAI/ak0t08B5brLTkjsOwJ/XyMVqjVlcAAOuPHvzPKvUmpdQaFS6Be+egpZP45TljJ1zEbpZp6VbU4=
  secret_access_key:
    secure: FQTmN9/VpQ+DFq8ohxdDMe94iGjefzOacz+bzDvTmYY1NL8QsW38lofZxxsSCY1FmbGY0twLbbBH7HKw8SX2Ay7SsR/5WjIL3o6/mOF3mvJtxjjdWkX50GLRBzn46YPXKFH+bId1EJ55HVEmb71YqzGeXHItU6gTp20vD2BMU8E=
  app-id: 93744a30-44d3-4437-9fc5-66302f758848
